/** Carnegie classification and religious affiliation code-to-label maps. */

export const carnegieLabels: Record<number, string> = {
  // Doctorate-granting
  15: "Doctoral University — Very High Research",
  16: "Doctoral University — High Research",
  17: "Doctoral/Professional University",
  // Master's
  18: "Master's College — Larger Programs",
  19: "Master's College — Medium Programs",
  20: "Master's College — Small Programs",
  // Baccalaureate
  21: "Baccalaureate College — Arts & Sciences",
  22: "Baccalaureate College — Diverse Fields",
  23: "Baccalaureate/Associate's College",
  // Associate's
  1: "Associate's — Public Rural-serving Small",
  2: "Associate's — Public Rural-serving Medium",
  3: "Associate's — Public Rural-serving Large",
  4: "Associate's — Public Suburban-serving Single Campus",
  5: "Associate's — Public Suburban-serving Multi Campus",
  6: "Associate's — Public Urban-serving Single Campus",
  7: "Associate's — Public Urban-serving Multi Campus",
  8: "Associate's — Public Special Use",
  9: "Associate's — Private Not-for-Profit",
  10: "Associate's — Private For-Profit",
  11: "Associate's — Public 2-year Under 4-year",
  12: "Associate's — Public 4-year Under 4-year",
  13: "Associate's — Private Not-for-Profit 4-year Under 4-year",
  14: "Associate's — Private For-Profit 4-year Under 4-year",
  // Special focus
  24: "Special Focus — Faith-Related",
  25: "Special Focus — Medical",
  26: "Special Focus — Health Professions",
  27: "Special Focus — Engineering",
  28: "Special Focus — Technology",
  29: "Special Focus — Business & Management",
  30: "Special Focus — Arts, Music & Design",
  31: "Special Focus — Law",
  32: "Special Focus — Other",
  33: "Tribal College",
  "-2": "Not classified",
};

export function carnegieLabel(code: number | null): string {
  if (code == null) return "Not classified";
  return carnegieLabels[code] ?? "Not classified";
}

export const religiousLabels: Record<number, string> = {
  22: "American Evangelical Lutheran",
  24: "African Methodist Episcopal",
  27: "Assemblies of God",
  28: "Brethren Church",
  30: "Roman Catholic",
  33: "Christian",
  34: "Christian Methodist Episcopal",
  35: "Church of Christ",
  36: "Church of God",
  37: "Churches of Christ",
  38: "Church of the Nazarene",
  39: "Cumberland Presbyterian",
  40: "Christian Reformed",
  41: "Episcopal/Anglican",
  43: "Free Will Baptist",
  44: "Friends (Quaker)",
  45: "Free Methodist",
  47: "General Baptist",
  48: "Greek Orthodox",
  49: "Jewish",
  50: "Latter Day Saints",
  51: "Lutheran Church — Missouri Synod",
  52: "Mennonite Brethren",
  53: "Moravian",
  54: "Mennonite",
  55: "Methodist",
  57: "Missionary Church",
  58: "Non-denominational",
  59: "North American Baptist",
  60: "Pentecostal Holiness",
  61: "Christian Churches / Churches of Christ",
  64: "Presbyterian (USA)",
  65: "Protestant Episcopal",
  66: "Reformed Presbyterian",
  67: "Reformed Church in America",
  68: "Reformed",
  69: "Russian Orthodox",
  71: "Seventh Day Adventist",
  73: "Southern Baptist",
  74: "United Brethren in Christ",
  75: "United Church of Christ",
  76: "United Methodist",
  77: "Unitarian Universalist",
  78: "Wesleyan",
  79: "Wisconsin Evangelical Lutheran Synod",
  80: "Other Protestant",
  81: "Other (not classified)",
  84: "Buddhist",
  87: "Evangelical Lutheran",
  88: "Hindu",
  89: "Islamic",
  91: "Interdenominational",
  92: "Presbyterian Church (USA)",
  93: "Evangelical Covenant",
  94: "Evangelical Free Church of America",
  95: "Evangelical",
  97: "Presbyterian",
  99: "Other",
  100: "Baptist",
  101: "Independent Non-Denominational",
  102: "American Baptist",
  103: "Sikh",
  105: "Original Free Will Baptist",
  "-1": "Not applicable",
  "-2": "Not available",
};

export function religiousLabel(code: number | null): string {
  if (code == null || code === -1) return "Not affiliated";
  return religiousLabels[code] ?? "Not affiliated";
}
